---
collections:
  - name: kubernetes.core
    version: 2.1.1
  - name: community.kubernetes
    version: 1.2.1
  - name: community.kubevirt
  - name: community.okd
  - name: community.vmware
  - name: oatakan.windows_cluster
  - name: oatakan.windows_sql_server