---
- name: provision sql nodes
  hosts: localhost
  become: false
  vars:
    provider: vmware
  vars_files:
    - node-config/sql-nodes-{{ provider }}.yml
  pre_tasks:
    - name: get amis on ec2
      ansible.builtin.include_role:
        name: ec2-find-amis
      when: provider == 'ec2'
  roles:
    - ansible-role-{{ provider }}
